import { library } from '@fortawesome/fontawesome-svg-core';
import {
  faHouseFlag,
  faBan,
  faGenderless,
  faVenus,
  faMars,
  faQuestionCircle,
  faHeartPulse,
  faSkullCrossbones,
  faCircleXmark,
  faMagnifyingGlass,
  faTrashRestore,
  faFilm,
  faMapLocationDot,
  faDna,
  faMicroscope,
  faLocationDot,
  faArrowsToCircle,
  faPeopleRoof,
  faCalendarDays,
} from '@fortawesome/free-solid-svg-icons';

library.add(
  faPeopleRoof,
  faLocationDot,
  faHouseFlag,
  faBan,
  faVenus,
  faMars,
  faHeartPulse,
  faQuestionCircle,
  faGenderless,
  faSkullCrossbones,
  faCircleXmark,
  faMagnifyingGlass,
  faTrashRestore,
  faFilm,
  faMapLocationDot,
  faDna,
  faMicroscope,
  faArrowsToCircle,
  faCalendarDays
);
